[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=2.11", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "solve_m_height_cpp"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["numpy"]

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
wheel.expand-macos-universal-tags = true

# Prefer single-config “Debug/Release” selector:
cmake.build-type = "Debug"   # change to "Release" for final wheel

# Pass-through definitions (optional)
cmake.define.SANITIZE = "ON"